### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined using SSR

### ISSUE THREAD

**Issue by futjikato** [joepuzzo/informed#23]
Running version 1.3.8

Getting this error when I try to render the simple example from the README via SSR .
@jangerhofer have you may encountered something like this when testing after #13 ?

```
{ TypeError: Cannot read property 'replace' of undefined
    at makePathArray (node_modules/informed/dist/index.js:1:23304)
    at ObjectMap.get (node_modules/informed/dist/index.js:1:25157)
    at Object.FormController.r.getValue (node_modules/informed/dist/index.js:1:28107)
    at buildFieldState (node_modules/informed/dist/index.js:1:4729)
    at new _class (node_modules/informed/dist/index.js:1:5858)
    at processChild (node_modules/react-dom/cjs/react-dom-server.node.development.js:2095:14)
    at resolve (node_modules/react-dom/cjs/react-dom-server.node.development.js:2061:5)
    at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:2380:22)
```

Thanks for the great work

**Comment by jangerhofer** [comment]
Hmm, I have not seen that one before nor can I grok what is going on in that line in the uglified, raw code.

I don't have any problem with a [toy reproduction repo](https://github.com/jangerhofer/informed-23/commit/a69e15dd86abea78b25cb5214e0f5b9fd458af00).  Would you try running my repo and/or creating your own?

**Comment by alaycock** [comment]
This happens for me when you leave the `field` prop undefined on the `Text` component.

```
import { Text } from "informed";
const a = () => <Text />;
```

**Comment by futjikato** [comment]
Yeah thanks for the catch @alaycock ... dont know how I missed that in my test.
